language: go
go:
  - "tip"
  - "1.2"

before_script:
  - go get code.google.com/p/go.tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - go test -covermode=count -coverprofile=cov.out
  - goveralls -coverprofile=cov.out -service=travis-ci