language: go
go:
  - "tip"
  - "1.2"

script:
  - go get code.google.com/p/go.tools/cmd/cover
  - go ge github.com/hailiang/goveralls
  - go test -covermode=count -coverprofile=profile.cov
  - goveralls -coverprofile=profile.cov -service=travis-ci