language: go
go:
  - "tip"
  - "1.2"

install:
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify
  - export PATH=$PATH:$HOME/gopath/bin/

script:
  - goveralls -v -service=travis-ci